import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'

const figtree = Figtree({ subsets: ['latin'], style: 'normal', weight: ['400', '500', '600', '700'] })

import { Header } from './components/Header'
import { Footer } from './components/Footer'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={figtree.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
